// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1_nQ5ZcDc_kb_rl4AQQzNavcaiOC2dCs',
    appId: '1:701344260261:web:00359b584a7399f95e6d4c',
    messagingSenderId: '701344260261',
    projectId: 'getwayaapp',
    authDomain: 'getwayaapp.firebaseapp.com',
    storageBucket: 'getwayaapp.appspot.com',
    measurementId: 'G-HFLX701THL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKJYjMKbxBgx-J4ea6KQXL3CauSBdKP50',
    appId: '1:701344260261:android:f96848cc547ccfeb5e6d4c',
    messagingSenderId: '701344260261',
    projectId: 'getwayaapp',
    storageBucket: 'getwayaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA8OMJBNCCC4aOhRnDG0JblLr570mIe5M',
    appId: '1:701344260261:ios:46828a6a7d936da15e6d4c',
    messagingSenderId: '701344260261',
    projectId: 'getwayaapp',
    storageBucket: 'getwayaapp.appspot.com',
    iosBundleId: 'com.example.getwayaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA8OMJBNCCC4aOhRnDG0JblLr570mIe5M',
    appId: '1:701344260261:ios:46828a6a7d936da15e6d4c',
    messagingSenderId: '701344260261',
    projectId: 'getwayaapp',
    storageBucket: 'getwayaapp.appspot.com',
    iosBundleId: 'com.example.getwayaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1_nQ5ZcDc_kb_rl4AQQzNavcaiOC2dCs',
    appId: '1:701344260261:web:d191af51ae1dc96c5e6d4c',
    messagingSenderId: '701344260261',
    projectId: 'getwayaapp',
    authDomain: 'getwayaapp.firebaseapp.com',
    storageBucket: 'getwayaapp.appspot.com',
    measurementId: 'G-KM4QRDQFKR',
  );
}
